import { useEffect } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAlertStore } from "@/stores/alertStore";
import type { Aircraft, Alert as AlertRow, Flight } from "@/lib/types";

let nextWoCounter = 9000;
function newWoNumber() {
  nextWoCounter += 1;
  return `WO-2026-${nextWoCounter}`;
}

async function insertAlert(payload: {
  type: string;
  severity: string;
  source_table: string;
  source_id: string;
  title: string;
  body: string;
  org_id: string;
}) {
  const { data, error } = await supabase.from("alerts").insert(payload).select().single();
  if (error) {
    console.error("[event-engine] insertAlert failed", error);
    return null;
  }
  return data as AlertRow;
}

/**
 * Run the full AOG cascade:
 *  1. Auto work order (Critical, AOG-Event)
 *  2. Affected crew → Fatigue-Hold + alert
 *  3. Affected cargo → Delayed + alert
 *  4. Master AOG alert
 */
export async function runAOGCascade(aircraft: Aircraft) {
  // 1. Work order
  const wo = {
    aircraft_id: aircraft.id,
    org_id: aircraft.org_id,
    work_order_number: newWoNumber(),
    title: `AOG: ${aircraft.tail_number} — Unscheduled Inspection Required`,
    description: `Auto-generated by event engine on AOG declaration at ${aircraft.current_airport ?? aircraft.base_airport}.`,
    status: "Open" as const,
    priority: "Critical",
    triggered_by: "AOG-Event",
  };
  await supabase.from("maintenance").insert(wo);

  // Find affected flights
  const { data: flights } = await supabase
    .from("flights")
    .select("id,flight_number")
    .eq("aircraft_id", aircraft.id);
  const flightIds = (flights ?? []).map((f) => f.id);

  let crewCount = 0;
  let cargoCount = 0;

  if (flightIds.length > 0) {
    // 2. Crew → Fatigue-Hold
    const { data: affectedCrew } = await supabase
      .from("crew")
      .select("id,full_name")
      .in("current_assignment", flightIds);
    crewCount = affectedCrew?.length ?? 0;
    if (crewCount > 0) {
      await supabase
        .from("crew")
        .update({ status: "Fatigue-Hold" as const, last_updated: new Date().toISOString() })
        .in("current_assignment", flightIds);
      await insertAlert({
        type: "FATIGUE",
        severity: "High",
        source_table: "aircraft",
        source_id: aircraft.id,
        title: `${crewCount} crew flagged Fatigue-Hold`,
        body: `${crewCount} crew member(s) assigned to flights on ${aircraft.tail_number} have been placed on fatigue hold.`,
      });
    }

    // 3. Cargo → Delayed
    const { data: affectedCargo } = await supabase
      .from("cargo")
      .select("id")
      .in("flight_id", flightIds);
    cargoCount = affectedCargo?.length ?? 0;
    if (cargoCount > 0) {
      await supabase
        .from("cargo")
        .update({
          status: "Delayed" as const,
          delay_notified: true,
          last_updated: new Date().toISOString(),
        })
        .in("flight_id", flightIds);
      await insertAlert({
        type: "CARGO",
        severity: "Medium",
        source_table: "aircraft",
        source_id: aircraft.id,
        title: `${cargoCount} cargo shipments delayed`,
        body: `${cargoCount} AWB(s) on ${aircraft.tail_number} have been notified of delay.`,
      });
    }

    // Cascade flight delays
    await supabase
      .from("flights")
      .update({ status: "Delayed", delay_reason: `AOG: ${aircraft.tail_number}` })
      .in("id", flightIds);
  }

  // 4. Master AOG alert
  await insertAlert({
    type: "AOG",
    severity: "Critical",
    source_table: "aircraft",
    source_id: aircraft.id,
    title: `AOG DECLARED — ${aircraft.tail_number}`,
    body: `Aircraft ${aircraft.tail_number} at ${aircraft.current_airport ?? aircraft.base_airport} is AOG. Work order ${wo.work_order_number} auto-generated. ${crewCount} crew flagged. ${cargoCount} cargo shipments delayed.`,
  });
}

export async function declareAOG(aircraftId: string) {
  const { data: ac, error } = await supabase
    .from("aircraft")
    .update({ status: "AOG" as const, last_updated: new Date().toISOString() })
    .eq("id", aircraftId)
    .select()
    .single();
  if (error || !ac) {
    console.error("[event-engine] declareAOG failed", error);
    return;
  }
  await runAOGCascade(ac as Aircraft);
}

async function handlePredictiveDegradation(aircraft: Aircraft) {
  // Avoid duplicates: check existing predictive WO for this aircraft
  const { data: existing } = await supabase
    .from("maintenance")
    .select("id")
    .eq("aircraft_id", aircraft.id)
    .eq("triggered_by", "Predictive")
    .neq("status", "Completed")
    .limit(1);
  if (existing && existing.length > 0) return;

  await supabase.from("maintenance").insert({
    aircraft_id: aircraft.id,
    work_order_number: newWoNumber(),
    title: `Predictive: ${aircraft.tail_number} health below 10%`,
    description: `Auto-generated. Current health score: ${aircraft.health_score}.`,
    status: "Open" as const,
    priority: "High",
    triggered_by: "Predictive",
  });
  await insertAlert({
    type: "MAINTENANCE",
    severity: "High",
    source_table: "aircraft",
    source_id: aircraft.id,
    title: `Predictive maintenance — ${aircraft.tail_number}`,
    body: `Health score ${aircraft.health_score}% below critical threshold. Work order created.`,
  });
}

async function handleFlightDelay(flight: Flight) {
  const { data: cargo } = await supabase
    .from("cargo")
    .select("id")
    .eq("flight_id", flight.id);
  const count = cargo?.length ?? 0;
  if (count > 0) {
    await supabase
      .from("cargo")
      .update({ delay_notified: true, last_updated: new Date().toISOString() })
      .eq("flight_id", flight.id);
  }
  await insertAlert({
    type: "DELAY",
    severity: "Medium",
    source_table: "flights",
    source_id: flight.id,
    title: `Flight ${flight.flight_number} delayed`,
    body: `${flight.origin_icao} → ${flight.destination_icao} delayed. ${count} cargo shipment(s) notified.`,
  });
}

/** Hook: subscribes to realtime changes and runs the event engine. */
export function useEventEngine() {
  const pushAlert = useAlertStore((s) => s.push);
  const pushToast = useAlertStore((s) => s.pushToast);
  const queryClient = useQueryClient();

  useEffect(() => {
    // Initial load of unacked alerts
    void supabase
      .from("alerts")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(50)
      .then(({ data }) => {
        if (data) useAlertStore.getState().setAll(data as AlertRow[]);
      });

    const ch = supabase
      .channel("event-engine")
      .on(
        "postgres_changes",
        { event: "INSERT", schema: "public", table: "alerts" },
        (payload) => {
          const a = payload.new as AlertRow;
          pushAlert(a);
          if (a.severity === "Critical" || a.severity === "High") pushToast(a);
        },
      )
      .on(
        "postgres_changes",
        { event: "UPDATE", schema: "public", table: "aircraft" },
        async (payload) => {
          const next = payload.new as Aircraft;
          const prev = payload.old as Aircraft;
          queryClient.invalidateQueries({ queryKey: ["aircraft"] });
          if (next.status === "AOG" && prev?.status !== "AOG") {
            await runAOGCascade(next);
            queryClient.invalidateQueries();
          } else if (
            Number(next.health_score) < 10 &&
            Number(prev?.health_score ?? 100) >= 10
          ) {
            await handlePredictiveDegradation(next);
            queryClient.invalidateQueries({ queryKey: ["maintenance"] });
          }
        },
      )
      .on(
        "postgres_changes",
        { event: "UPDATE", schema: "public", table: "flights" },
        async (payload) => {
          const next = payload.new as Flight;
          const prev = payload.old as Flight;
          queryClient.invalidateQueries({ queryKey: ["flights"] });
          if (next.status === "Delayed" && prev?.status !== "Delayed") {
            await handleFlightDelay(next);
            queryClient.invalidateQueries({ queryKey: ["cargo"] });
          }
        },
      )
      .on(
        "postgres_changes",
        { event: "*", schema: "public", table: "crew" },
        () => queryClient.invalidateQueries({ queryKey: ["crew"] }),
      )
      .subscribe();

    return () => {
      void supabase.removeChannel(ch);
    };
  }, [pushAlert, pushToast, queryClient]);
}
