import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { AircraftCardData } from "@/components/fleet/AircraftCard";

export async function exportFleetSnapshotPdf(
  fleet: AircraftCardData[],
  orgName: string,
): Promise<void> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const page = pdf.addPage([595, 842]); // A4
  const { width, height } = page.getSize();
  let y = height - 50;

  page.drawText("SKYTRACK — Fleet Snapshot", {
    x: 40, y, size: 18, font: bold, color: rgb(0.05, 0.65, 0.91),
  });
  y -= 22;
  page.drawText(`${orgName} · ${new Date().toUTCString()}`, {
    x: 40, y, size: 10, font, color: rgb(0.4, 0.4, 0.5),
  });
  y -= 30;

  // Header row
  const cols = [
    { label: "TAIL", x: 40, w: 70 },
    { label: "MODEL", x: 110, w: 120 },
    { label: "STATUS", x: 230, w: 80 },
    { label: "HEALTH", x: 310, w: 55 },
    { label: "HOURS", x: 365, w: 60 },
    { label: "BASE", x: 425, w: 60 },
    { label: "NEXT INSP", x: 485, w: 70 },
  ];
  page.drawRectangle({ x: 40, y: y - 4, width: width - 80, height: 18, color: rgb(0.93, 0.95, 0.98) });
  cols.forEach((c) =>
    page.drawText(c.label, { x: c.x + 2, y, size: 8, font: bold, color: rgb(0.2, 0.2, 0.3) }),
  );
  y -= 18;

  for (const a of fleet) {
    if (y < 60) {
      const next = pdf.addPage([595, 842]);
      y = next.getSize().height - 50;
    }
    const row = [
      a.tail_number,
      a.model.slice(0, 20),
      a.status,
      `${Math.round(a.health_score)}%`,
      `${a.total_flight_hours ?? 0}`,
      a.base_airport_icao ?? "—",
      a.next_inspection ?? "—",
    ];
    const color =
      a.status === "AOG" ? rgb(0.93, 0.27, 0.27) :
      a.status === "Maintenance" ? rgb(0.96, 0.62, 0.04) :
      rgb(0.1, 0.1, 0.15);
    row.forEach((val, i) => {
      page.drawText(String(val), { x: cols[i].x + 2, y, size: 9, font, color });
    });
    y -= 16;
  }

  // Footer
  page.drawText("Generated by SkyTrack AAOS — confidential", {
    x: 40, y: 30, size: 8, font, color: rgb(0.5, 0.5, 0.6),
  });

  const bytes = await pdf.save();
  const blob = new Blob([bytes as BlobPart], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `skytrack-fleet-${new Date().toISOString().slice(0, 10)}.pdf`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
