/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRoutingRouteImport } from './routes/_authenticated/routing'
import { Route as AuthenticatedMroRouteImport } from './routes/_authenticated/mro'
import { Route as AuthenticatedFlightsRouteImport } from './routes/_authenticated/flights'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated/fleet'
import { Route as AuthenticatedDisruptionRouteImport } from './routes/_authenticated/disruption'
import { Route as AuthenticatedCrewRouteImport } from './routes/_authenticated/crew'
import { Route as AuthenticatedCargoRouteImport } from './routes/_authenticated/cargo'
import { Route as AuthenticatedCarbonRouteImport } from './routes/_authenticated/carbon'
import { Route as AuthenticatedCrewIdRouteImport } from './routes/_authenticated/crew.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutingRoute = AuthenticatedRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMroRoute = AuthenticatedMroRouteImport.update({
  id: '/mro',
  path: '/mro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlightsRoute = AuthenticatedFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDisruptionRoute = AuthenticatedDisruptionRouteImport.update({
  id: '/disruption',
  path: '/disruption',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrewRoute = AuthenticatedCrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCargoRoute = AuthenticatedCargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCarbonRoute = AuthenticatedCarbonRouteImport.update({
  id: '/carbon',
  path: '/carbon',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrewIdRoute = AuthenticatedCrewIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCrewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/carbon': typeof AuthenticatedCarbonRoute
  '/cargo': typeof AuthenticatedCargoRoute
  '/crew': typeof AuthenticatedCrewRouteWithChildren
  '/disruption': typeof AuthenticatedDisruptionRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/flights': typeof AuthenticatedFlightsRoute
  '/mro': typeof AuthenticatedMroRoute
  '/routing': typeof AuthenticatedRoutingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/crew/$id': typeof AuthenticatedCrewIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/carbon': typeof AuthenticatedCarbonRoute
  '/cargo': typeof AuthenticatedCargoRoute
  '/crew': typeof AuthenticatedCrewRouteWithChildren
  '/disruption': typeof AuthenticatedDisruptionRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/flights': typeof AuthenticatedFlightsRoute
  '/mro': typeof AuthenticatedMroRoute
  '/routing': typeof AuthenticatedRoutingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/crew/$id': typeof AuthenticatedCrewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/carbon': typeof AuthenticatedCarbonRoute
  '/_authenticated/cargo': typeof AuthenticatedCargoRoute
  '/_authenticated/crew': typeof AuthenticatedCrewRouteWithChildren
  '/_authenticated/disruption': typeof AuthenticatedDisruptionRoute
  '/_authenticated/fleet': typeof AuthenticatedFleetRoute
  '/_authenticated/flights': typeof AuthenticatedFlightsRoute
  '/_authenticated/mro': typeof AuthenticatedMroRoute
  '/_authenticated/routing': typeof AuthenticatedRoutingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/crew/$id': typeof AuthenticatedCrewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/carbon'
    | '/cargo'
    | '/crew'
    | '/disruption'
    | '/fleet'
    | '/flights'
    | '/mro'
    | '/routing'
    | '/settings'
    | '/crew/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/carbon'
    | '/cargo'
    | '/crew'
    | '/disruption'
    | '/fleet'
    | '/flights'
    | '/mro'
    | '/routing'
    | '/settings'
    | '/'
    | '/crew/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/carbon'
    | '/_authenticated/cargo'
    | '/_authenticated/crew'
    | '/_authenticated/disruption'
    | '/_authenticated/fleet'
    | '/_authenticated/flights'
    | '/_authenticated/mro'
    | '/_authenticated/routing'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/crew/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routing': {
      id: '/_authenticated/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof AuthenticatedRoutingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mro': {
      id: '/_authenticated/mro'
      path: '/mro'
      fullPath: '/mro'
      preLoaderRoute: typeof AuthenticatedMroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flights': {
      id: '/_authenticated/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof AuthenticatedFlightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/disruption': {
      id: '/_authenticated/disruption'
      path: '/disruption'
      fullPath: '/disruption'
      preLoaderRoute: typeof AuthenticatedDisruptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crew': {
      id: '/_authenticated/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof AuthenticatedCrewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cargo': {
      id: '/_authenticated/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof AuthenticatedCargoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/carbon': {
      id: '/_authenticated/carbon'
      path: '/carbon'
      fullPath: '/carbon'
      preLoaderRoute: typeof AuthenticatedCarbonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crew/$id': {
      id: '/_authenticated/crew/$id'
      path: '/$id'
      fullPath: '/crew/$id'
      preLoaderRoute: typeof AuthenticatedCrewIdRouteImport
      parentRoute: typeof AuthenticatedCrewRoute
    }
  }
}

interface AuthenticatedCrewRouteChildren {
  AuthenticatedCrewIdRoute: typeof AuthenticatedCrewIdRoute
}

const AuthenticatedCrewRouteChildren: AuthenticatedCrewRouteChildren = {
  AuthenticatedCrewIdRoute: AuthenticatedCrewIdRoute,
}

const AuthenticatedCrewRouteWithChildren =
  AuthenticatedCrewRoute._addFileChildren(AuthenticatedCrewRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCarbonRoute: typeof AuthenticatedCarbonRoute
  AuthenticatedCargoRoute: typeof AuthenticatedCargoRoute
  AuthenticatedCrewRoute: typeof AuthenticatedCrewRouteWithChildren
  AuthenticatedDisruptionRoute: typeof AuthenticatedDisruptionRoute
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRoute
  AuthenticatedFlightsRoute: typeof AuthenticatedFlightsRoute
  AuthenticatedMroRoute: typeof AuthenticatedMroRoute
  AuthenticatedRoutingRoute: typeof AuthenticatedRoutingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCarbonRoute: AuthenticatedCarbonRoute,
  AuthenticatedCargoRoute: AuthenticatedCargoRoute,
  AuthenticatedCrewRoute: AuthenticatedCrewRouteWithChildren,
  AuthenticatedDisruptionRoute: AuthenticatedDisruptionRoute,
  AuthenticatedFleetRoute: AuthenticatedFleetRoute,
  AuthenticatedFlightsRoute: AuthenticatedFlightsRoute,
  AuthenticatedMroRoute: AuthenticatedMroRoute,
  AuthenticatedRoutingRoute: AuthenticatedRoutingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
