/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as GuideAircraftManagementRouteImport } from './routes/guide.aircraft-management'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedWeatherRiskRouteImport } from './routes/_authenticated/weather-risk'
import { Route as AuthenticatedTrackerRouteImport } from './routes/_authenticated/tracker'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated/superadmin'
import { Route as AuthenticatedSimulatorRouteImport } from './routes/_authenticated/simulator'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRoutingRouteImport } from './routes/_authenticated/routing'
import { Route as AuthenticatedRegulatorRouteImport } from './routes/_authenticated/regulator'
import { Route as AuthenticatedPredictiveRouteImport } from './routes/_authenticated/predictive'
import { Route as AuthenticatedPitchRouteImport } from './routes/_authenticated/pitch'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated/pending'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMroRouteImport } from './routes/_authenticated/mro'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedLogbookRouteImport } from './routes/_authenticated/logbook'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedFuelBurnRouteImport } from './routes/_authenticated/fuel-burn'
import { Route as AuthenticatedFlightsRouteImport } from './routes/_authenticated/flights'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated/fleet'
import { Route as AuthenticatedDisruptionRouteImport } from './routes/_authenticated/disruption'
import { Route as AuthenticatedCrewRouteImport } from './routes/_authenticated/crew'
import { Route as AuthenticatedCargoRouteImport } from './routes/_authenticated/cargo'
import { Route as AuthenticatedCarbonRouteImport } from './routes/_authenticated/carbon'
import { Route as AuthenticatedBrandingRouteImport } from './routes/_authenticated/branding'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedAllocationRouteImport } from './routes/_authenticated/allocation'
import { Route as AuthenticatedAdsbStatusRouteImport } from './routes/_authenticated/adsb-status'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedFlightsIdRouteImport } from './routes/_authenticated/flights.$id'
import { Route as AuthenticatedFleetIdRouteImport } from './routes/_authenticated/fleet.$id'
import { Route as AuthenticatedCrewIdRouteImport } from './routes/_authenticated/crew.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicV1OpenapiJsonRouteImport } from './routes/api/public/v1.openapi.json'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const GuideAircraftManagementRoute = GuideAircraftManagementRouteImport.update({
  id: '/guide/aircraft-management',
  path: '/guide/aircraft-management',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeatherRiskRoute =
  AuthenticatedWeatherRiskRouteImport.update({
    id: '/weather-risk',
    path: '/weather-risk',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrackerRoute = AuthenticatedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSimulatorRoute = AuthenticatedSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutingRoute = AuthenticatedRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRegulatorRoute = AuthenticatedRegulatorRouteImport.update({
  id: '/regulator',
  path: '/regulator',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPredictiveRoute = AuthenticatedPredictiveRouteImport.update({
  id: '/predictive',
  path: '/predictive',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPitchRoute = AuthenticatedPitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMroRoute = AuthenticatedMroRouteImport.update({
  id: '/mro',
  path: '/mro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogbookRoute = AuthenticatedLogbookRouteImport.update({
  id: '/logbook',
  path: '/logbook',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFuelBurnRoute = AuthenticatedFuelBurnRouteImport.update({
  id: '/fuel-burn',
  path: '/fuel-burn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlightsRoute = AuthenticatedFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDisruptionRoute = AuthenticatedDisruptionRouteImport.update({
  id: '/disruption',
  path: '/disruption',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrewRoute = AuthenticatedCrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCargoRoute = AuthenticatedCargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCarbonRoute = AuthenticatedCarbonRouteImport.update({
  id: '/carbon',
  path: '/carbon',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrandingRoute = AuthenticatedBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAllocationRoute = AuthenticatedAllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdsbStatusRoute = AuthenticatedAdsbStatusRouteImport.update({
  id: '/adsb-status',
  path: '/adsb-status',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedFlightsIdRoute = AuthenticatedFlightsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedFlightsRoute,
} as any)
const AuthenticatedFleetIdRoute = AuthenticatedFleetIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedFleetRoute,
} as any)
const AuthenticatedCrewIdRoute = AuthenticatedCrewIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCrewRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OpenapiJsonRoute = ApiPublicV1OpenapiJsonRouteImport.update({
  id: '/api/public/v1/openapi/json',
  path: '/api/public/v1/openapi/json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/trust': typeof TrustRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/adsb-status': typeof AuthenticatedAdsbStatusRoute
  '/allocation': typeof AuthenticatedAllocationRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/branding': typeof AuthenticatedBrandingRoute
  '/carbon': typeof AuthenticatedCarbonRoute
  '/cargo': typeof AuthenticatedCargoRoute
  '/crew': typeof AuthenticatedCrewRouteWithChildren
  '/disruption': typeof AuthenticatedDisruptionRoute
  '/fleet': typeof AuthenticatedFleetRouteWithChildren
  '/flights': typeof AuthenticatedFlightsRouteWithChildren
  '/fuel-burn': typeof AuthenticatedFuelBurnRoute
  '/import': typeof AuthenticatedImportRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/logbook': typeof AuthenticatedLogbookRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/mro': typeof AuthenticatedMroRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/pitch': typeof AuthenticatedPitchRoute
  '/predictive': typeof AuthenticatedPredictiveRoute
  '/regulator': typeof AuthenticatedRegulatorRoute
  '/routing': typeof AuthenticatedRoutingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/simulator': typeof AuthenticatedSimulatorRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/weather-risk': typeof AuthenticatedWeatherRiskRoute
  '/api/chat': typeof ApiChatRoute
  '/docs/api': typeof DocsApiRoute
  '/guide/aircraft-management': typeof GuideAircraftManagementRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/crew/$id': typeof AuthenticatedCrewIdRoute
  '/fleet/$id': typeof AuthenticatedFleetIdRoute
  '/flights/$id': typeof AuthenticatedFlightsIdRoute
  '/api/public/v1/openapi/json': typeof ApiPublicV1OpenapiJsonRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/trust': typeof TrustRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/adsb-status': typeof AuthenticatedAdsbStatusRoute
  '/allocation': typeof AuthenticatedAllocationRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/branding': typeof AuthenticatedBrandingRoute
  '/carbon': typeof AuthenticatedCarbonRoute
  '/cargo': typeof AuthenticatedCargoRoute
  '/crew': typeof AuthenticatedCrewRouteWithChildren
  '/disruption': typeof AuthenticatedDisruptionRoute
  '/fleet': typeof AuthenticatedFleetRouteWithChildren
  '/flights': typeof AuthenticatedFlightsRouteWithChildren
  '/fuel-burn': typeof AuthenticatedFuelBurnRoute
  '/import': typeof AuthenticatedImportRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/logbook': typeof AuthenticatedLogbookRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/mro': typeof AuthenticatedMroRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/pitch': typeof AuthenticatedPitchRoute
  '/predictive': typeof AuthenticatedPredictiveRoute
  '/regulator': typeof AuthenticatedRegulatorRoute
  '/routing': typeof AuthenticatedRoutingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/simulator': typeof AuthenticatedSimulatorRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/weather-risk': typeof AuthenticatedWeatherRiskRoute
  '/api/chat': typeof ApiChatRoute
  '/docs/api': typeof DocsApiRoute
  '/guide/aircraft-management': typeof GuideAircraftManagementRoute
  '/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/crew/$id': typeof AuthenticatedCrewIdRoute
  '/fleet/$id': typeof AuthenticatedFleetIdRoute
  '/flights/$id': typeof AuthenticatedFlightsIdRoute
  '/api/public/v1/openapi/json': typeof ApiPublicV1OpenapiJsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/trust': typeof TrustRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/adsb-status': typeof AuthenticatedAdsbStatusRoute
  '/_authenticated/allocation': typeof AuthenticatedAllocationRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/branding': typeof AuthenticatedBrandingRoute
  '/_authenticated/carbon': typeof AuthenticatedCarbonRoute
  '/_authenticated/cargo': typeof AuthenticatedCargoRoute
  '/_authenticated/crew': typeof AuthenticatedCrewRouteWithChildren
  '/_authenticated/disruption': typeof AuthenticatedDisruptionRoute
  '/_authenticated/fleet': typeof AuthenticatedFleetRouteWithChildren
  '/_authenticated/flights': typeof AuthenticatedFlightsRouteWithChildren
  '/_authenticated/fuel-burn': typeof AuthenticatedFuelBurnRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/logbook': typeof AuthenticatedLogbookRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/mro': typeof AuthenticatedMroRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/_authenticated/pitch': typeof AuthenticatedPitchRoute
  '/_authenticated/predictive': typeof AuthenticatedPredictiveRoute
  '/_authenticated/regulator': typeof AuthenticatedRegulatorRoute
  '/_authenticated/routing': typeof AuthenticatedRoutingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/simulator': typeof AuthenticatedSimulatorRoute
  '/_authenticated/superadmin': typeof AuthenticatedSuperadminRoute
  '/_authenticated/tracker': typeof AuthenticatedTrackerRoute
  '/_authenticated/weather-risk': typeof AuthenticatedWeatherRiskRoute
  '/api/chat': typeof ApiChatRoute
  '/docs/api': typeof DocsApiRoute
  '/guide/aircraft-management': typeof GuideAircraftManagementRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/crew/$id': typeof AuthenticatedCrewIdRoute
  '/_authenticated/fleet/$id': typeof AuthenticatedFleetIdRoute
  '/_authenticated/flights/$id': typeof AuthenticatedFlightsIdRoute
  '/api/public/v1/openapi/json': typeof ApiPublicV1OpenapiJsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/sitemap.xml'
    | '/status'
    | '/trust'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/adsb-status'
    | '/allocation'
    | '/approvals'
    | '/audit'
    | '/branding'
    | '/carbon'
    | '/cargo'
    | '/crew'
    | '/disruption'
    | '/fleet'
    | '/flights'
    | '/fuel-burn'
    | '/import'
    | '/integrations'
    | '/logbook'
    | '/marketplace'
    | '/mro'
    | '/onboarding'
    | '/pending'
    | '/pitch'
    | '/predictive'
    | '/regulator'
    | '/routing'
    | '/settings'
    | '/simulator'
    | '/superadmin'
    | '/tracker'
    | '/weather-risk'
    | '/api/chat'
    | '/docs/api'
    | '/guide/aircraft-management'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/crew/$id'
    | '/fleet/$id'
    | '/flights/$id'
    | '/api/public/v1/openapi/json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/mcp'
    | '/sitemap.xml'
    | '/status'
    | '/trust'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/adsb-status'
    | '/allocation'
    | '/approvals'
    | '/audit'
    | '/branding'
    | '/carbon'
    | '/cargo'
    | '/crew'
    | '/disruption'
    | '/fleet'
    | '/flights'
    | '/fuel-burn'
    | '/import'
    | '/integrations'
    | '/logbook'
    | '/marketplace'
    | '/mro'
    | '/onboarding'
    | '/pending'
    | '/pitch'
    | '/predictive'
    | '/regulator'
    | '/routing'
    | '/settings'
    | '/simulator'
    | '/superadmin'
    | '/tracker'
    | '/weather-risk'
    | '/api/chat'
    | '/docs/api'
    | '/guide/aircraft-management'
    | '/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/crew/$id'
    | '/fleet/$id'
    | '/flights/$id'
    | '/api/public/v1/openapi/json'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/mcp'
    | '/sitemap.xml'
    | '/status'
    | '/trust'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/adsb-status'
    | '/_authenticated/allocation'
    | '/_authenticated/approvals'
    | '/_authenticated/audit'
    | '/_authenticated/branding'
    | '/_authenticated/carbon'
    | '/_authenticated/cargo'
    | '/_authenticated/crew'
    | '/_authenticated/disruption'
    | '/_authenticated/fleet'
    | '/_authenticated/flights'
    | '/_authenticated/fuel-burn'
    | '/_authenticated/import'
    | '/_authenticated/integrations'
    | '/_authenticated/logbook'
    | '/_authenticated/marketplace'
    | '/_authenticated/mro'
    | '/_authenticated/onboarding'
    | '/_authenticated/pending'
    | '/_authenticated/pitch'
    | '/_authenticated/predictive'
    | '/_authenticated/regulator'
    | '/_authenticated/routing'
    | '/_authenticated/settings'
    | '/_authenticated/simulator'
    | '/_authenticated/superadmin'
    | '/_authenticated/tracker'
    | '/_authenticated/weather-risk'
    | '/api/chat'
    | '/docs/api'
    | '/guide/aircraft-management'
    | '/_authenticated/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/crew/$id'
    | '/_authenticated/fleet/$id'
    | '/_authenticated/flights/$id'
    | '/api/public/v1/openapi/json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  TrustRoute: typeof TrustRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  DocsApiRoute: typeof DocsApiRoute
  GuideAircraftManagementRoute: typeof GuideAircraftManagementRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicV1OpenapiJsonRoute: typeof ApiPublicV1OpenapiJsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/guide/aircraft-management': {
      id: '/guide/aircraft-management'
      path: '/guide/aircraft-management'
      fullPath: '/guide/aircraft-management'
      preLoaderRoute: typeof GuideAircraftManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weather-risk': {
      id: '/_authenticated/weather-risk'
      path: '/weather-risk'
      fullPath: '/weather-risk'
      preLoaderRoute: typeof AuthenticatedWeatherRiskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tracker': {
      id: '/_authenticated/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthenticatedTrackerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/superadmin': {
      id: '/_authenticated/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simulator': {
      id: '/_authenticated/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof AuthenticatedSimulatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routing': {
      id: '/_authenticated/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof AuthenticatedRoutingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/regulator': {
      id: '/_authenticated/regulator'
      path: '/regulator'
      fullPath: '/regulator'
      preLoaderRoute: typeof AuthenticatedRegulatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/predictive': {
      id: '/_authenticated/predictive'
      path: '/predictive'
      fullPath: '/predictive'
      preLoaderRoute: typeof AuthenticatedPredictiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pitch': {
      id: '/_authenticated/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof AuthenticatedPitchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mro': {
      id: '/_authenticated/mro'
      path: '/mro'
      fullPath: '/mro'
      preLoaderRoute: typeof AuthenticatedMroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logbook': {
      id: '/_authenticated/logbook'
      path: '/logbook'
      fullPath: '/logbook'
      preLoaderRoute: typeof AuthenticatedLogbookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fuel-burn': {
      id: '/_authenticated/fuel-burn'
      path: '/fuel-burn'
      fullPath: '/fuel-burn'
      preLoaderRoute: typeof AuthenticatedFuelBurnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flights': {
      id: '/_authenticated/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof AuthenticatedFlightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/disruption': {
      id: '/_authenticated/disruption'
      path: '/disruption'
      fullPath: '/disruption'
      preLoaderRoute: typeof AuthenticatedDisruptionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crew': {
      id: '/_authenticated/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof AuthenticatedCrewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cargo': {
      id: '/_authenticated/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof AuthenticatedCargoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/carbon': {
      id: '/_authenticated/carbon'
      path: '/carbon'
      fullPath: '/carbon'
      preLoaderRoute: typeof AuthenticatedCarbonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branding': {
      id: '/_authenticated/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof AuthenticatedBrandingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/allocation': {
      id: '/_authenticated/allocation'
      path: '/allocation'
      fullPath: '/allocation'
      preLoaderRoute: typeof AuthenticatedAllocationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adsb-status': {
      id: '/_authenticated/adsb-status'
      path: '/adsb-status'
      fullPath: '/adsb-status'
      preLoaderRoute: typeof AuthenticatedAdsbStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/flights/$id': {
      id: '/_authenticated/flights/$id'
      path: '/$id'
      fullPath: '/flights/$id'
      preLoaderRoute: typeof AuthenticatedFlightsIdRouteImport
      parentRoute: typeof AuthenticatedFlightsRoute
    }
    '/_authenticated/fleet/$id': {
      id: '/_authenticated/fleet/$id'
      path: '/$id'
      fullPath: '/fleet/$id'
      preLoaderRoute: typeof AuthenticatedFleetIdRouteImport
      parentRoute: typeof AuthenticatedFleetRoute
    }
    '/_authenticated/crew/$id': {
      id: '/_authenticated/crew/$id'
      path: '/$id'
      fullPath: '/crew/$id'
      preLoaderRoute: typeof AuthenticatedCrewIdRouteImport
      parentRoute: typeof AuthenticatedCrewRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/openapi/json': {
      id: '/api/public/v1/openapi/json'
      path: '/api/public/v1/openapi/json'
      fullPath: '/api/public/v1/openapi/json'
      preLoaderRoute: typeof ApiPublicV1OpenapiJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCrewRouteChildren {
  AuthenticatedCrewIdRoute: typeof AuthenticatedCrewIdRoute
}

const AuthenticatedCrewRouteChildren: AuthenticatedCrewRouteChildren = {
  AuthenticatedCrewIdRoute: AuthenticatedCrewIdRoute,
}

const AuthenticatedCrewRouteWithChildren =
  AuthenticatedCrewRoute._addFileChildren(AuthenticatedCrewRouteChildren)

interface AuthenticatedFleetRouteChildren {
  AuthenticatedFleetIdRoute: typeof AuthenticatedFleetIdRoute
}

const AuthenticatedFleetRouteChildren: AuthenticatedFleetRouteChildren = {
  AuthenticatedFleetIdRoute: AuthenticatedFleetIdRoute,
}

const AuthenticatedFleetRouteWithChildren =
  AuthenticatedFleetRoute._addFileChildren(AuthenticatedFleetRouteChildren)

interface AuthenticatedFlightsRouteChildren {
  AuthenticatedFlightsIdRoute: typeof AuthenticatedFlightsIdRoute
}

const AuthenticatedFlightsRouteChildren: AuthenticatedFlightsRouteChildren = {
  AuthenticatedFlightsIdRoute: AuthenticatedFlightsIdRoute,
}

const AuthenticatedFlightsRouteWithChildren =
  AuthenticatedFlightsRoute._addFileChildren(AuthenticatedFlightsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdsbStatusRoute: typeof AuthenticatedAdsbStatusRoute
  AuthenticatedAllocationRoute: typeof AuthenticatedAllocationRoute
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBrandingRoute: typeof AuthenticatedBrandingRoute
  AuthenticatedCarbonRoute: typeof AuthenticatedCarbonRoute
  AuthenticatedCargoRoute: typeof AuthenticatedCargoRoute
  AuthenticatedCrewRoute: typeof AuthenticatedCrewRouteWithChildren
  AuthenticatedDisruptionRoute: typeof AuthenticatedDisruptionRoute
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRouteWithChildren
  AuthenticatedFlightsRoute: typeof AuthenticatedFlightsRouteWithChildren
  AuthenticatedFuelBurnRoute: typeof AuthenticatedFuelBurnRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedLogbookRoute: typeof AuthenticatedLogbookRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedMroRoute: typeof AuthenticatedMroRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
  AuthenticatedPitchRoute: typeof AuthenticatedPitchRoute
  AuthenticatedPredictiveRoute: typeof AuthenticatedPredictiveRoute
  AuthenticatedRegulatorRoute: typeof AuthenticatedRegulatorRoute
  AuthenticatedRoutingRoute: typeof AuthenticatedRoutingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSimulatorRoute: typeof AuthenticatedSimulatorRoute
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRoute
  AuthenticatedTrackerRoute: typeof AuthenticatedTrackerRoute
  AuthenticatedWeatherRiskRoute: typeof AuthenticatedWeatherRiskRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdsbStatusRoute: AuthenticatedAdsbStatusRoute,
  AuthenticatedAllocationRoute: AuthenticatedAllocationRoute,
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBrandingRoute: AuthenticatedBrandingRoute,
  AuthenticatedCarbonRoute: AuthenticatedCarbonRoute,
  AuthenticatedCargoRoute: AuthenticatedCargoRoute,
  AuthenticatedCrewRoute: AuthenticatedCrewRouteWithChildren,
  AuthenticatedDisruptionRoute: AuthenticatedDisruptionRoute,
  AuthenticatedFleetRoute: AuthenticatedFleetRouteWithChildren,
  AuthenticatedFlightsRoute: AuthenticatedFlightsRouteWithChildren,
  AuthenticatedFuelBurnRoute: AuthenticatedFuelBurnRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedLogbookRoute: AuthenticatedLogbookRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedMroRoute: AuthenticatedMroRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
  AuthenticatedPitchRoute: AuthenticatedPitchRoute,
  AuthenticatedPredictiveRoute: AuthenticatedPredictiveRoute,
  AuthenticatedRegulatorRoute: AuthenticatedRegulatorRoute,
  AuthenticatedRoutingRoute: AuthenticatedRoutingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSimulatorRoute: AuthenticatedSimulatorRoute,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRoute,
  AuthenticatedTrackerRoute: AuthenticatedTrackerRoute,
  AuthenticatedWeatherRiskRoute: AuthenticatedWeatherRiskRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  TrustRoute: TrustRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  DocsApiRoute: DocsApiRoute,
  GuideAircraftManagementRoute: GuideAircraftManagementRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicV1OpenapiJsonRoute: ApiPublicV1OpenapiJsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
